---
deployment:
  tasks:
    - export DEPLOYMENT_TARGET=/home/flikportal/public_html/
    - /bin/cp -R . $DEPLOYMENT_TARGET
    - cd $DEPLOYMENT_TARGET
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run strict-build
    - /usr/local/bin/pm2 restart all
